spring:
  main:
    log-startup-info: true # логирование деталей старта разрешено
    banner-mode: off

logging.level:
  ru.yandex.practicum.quiz: INFO # настраиваем уровень логера

spring-quiz:
  report:
    mode: "concise"